version: "3"

services:
  fscorredores_apache:
    container_name: "fscorredores_apache"
    build:
      context: ./docker/apache
      args:
        APACHE_VERSION: "2.4.41"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    networks:
      fscorredores_network:
        ipv4_address: 172.21.0.2

  fscorredores_php:
    container_name: "fscorredores_php"
    build:
      context: ./docker/php
      args:
        PHP_VERSION: "5.6"
    volumes:
      - ./:/var/www/html/
    networks:
      fscorredores_network:
        ipv4_address: 172.21.0.3

  fscorredores_db:
    container_name: "fscorredores_db"
    image: "mysql:5.6"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf
    networks:
      fscorredores_network:
        ipv4_address: 172.21.0.4
    environment:
      - MYSQL_ROOT_PASSWORD=root

networks:
  fscorredores_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
